### ISSUE TITLE
Error in ListView component. Multiple selection of an item in the list.

### ISSUE THREAD

**Issue by patryk84a** [mit-cml/appinventor-sources#2283]
**Describe the bug**

After selecting one item in the list, more items are checked (highlighted). This only happens when the list is longer and scrolls. Link: https://community.appinventor.mit.edu/t/listview-selection-color-is-highlighting-every-5th-item-in-list/6117

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

When selecting one item on the list, only one should be selected.

**Steps to reproduce**

- add ListView to the project,
- add a list of any 6 elements,
- reduce the height of the list to around 100px
- compile the application or connect via companion,
- select any item from the list
- scroll through the list to see that more list items are selected

**Comment by ewpatton** [comment]
I believe this is fixed by #2170. @elatoskinas is my understanding correct?

**Comment by patryk84a** [comment]
Everyone thought so :). Unfortunately the problem is still in n184.

**Comment by ewpatton** [comment]
It hasn't been merged yet, so it not in that release.

**Comment by patryk84a** [comment]
Then I misunderstood the posts on the community saying that it should be fixed in n183 :). In that case, you can close and wait for the patch to be deployed :).

**Comment by sachin-0102** [comment]
If the issue is still open, Can I work on it

**Comment by BeksOmega** [comment]
> If the issue is still open, Can I work on it?

Hello @sachin-0102 I think this issue has already been handled, but there are some other issues we would love help on! Anything tagged with [help-wanted](https://github.com/mit-cml/appinventor-sources/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) is fair game. Since you were interested in this issue you might also like the [Add Patch method to Web Component](https://github.com/mit-cml/appinventor-sources/issues/2192) issue

**Comment by elatoskinas** [comment]
> I believe this is fixed by #2170. @elatoskinas is my understanding correct?

Indeed, the fix is handled in that pull request

**Comment by TimCarterLinux** [comment]
This issue is still not resolved, despite everyone's assertions that it has been fixed by #2170. It has not.

**Comment by patryk84a** [comment]
> Ten problem nadal nie został rozwiązany, pomimo zapewnień wszystkich, że został naprawiony przez [# 2170](https://github.com/mit-cml/appinventor-sources/pull/2170) . Nie ma.

![dddd](https://user-images.githubusercontent.com/62844519/117549631-cafbf100-b03b-11eb-9f87-78ddbd628c6a.jpg)

It will be in NB187
