### ISSUE TITLE
Block context menu displays erratic block counts

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#3390]
**Describe the bug**

Community thread: https://community.appinventor.mit.edu/t/display-amount-of-blocks-within-a-block/140347

When a block is right-clicked, one of the options in the context menu is to delete it and any connected blocks. The count for the number of connected block to delete in the menu text is wildly off in at least some circumstances. When the option is selected, the correct number of blocks is deleted.

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Context menu text should accurately reflect the number of connected blocks that would be deleted.

**Comment by patryk84a** [comment]
I looked at it, it looks like if we left click on the blocks and then right click to display the menu, the calculations are correct. However, if we immediately right click on the block, the calculations are displayed from the previous block clicked.

**Comment by josmas** [comment]
Doing a bit of digging here, I believe the problem is not that the counter is off, or at least I cannot reproduce that behaviour. Instead what the community thread says is that you have to right-click a block an indeterminate number of times to see the count. I cannot find a pattern, but the first time you right-click the text will read `Delete Block` but clicking subsequently it might read `Delete X Blocks`. See images.

<!-- Uploading "first_clcik.png"... —>
<!-- Uploading "second_click.png"... —>

It at times needs only two clicks, but at times more. The only way to `force` the count to refresh that I have found so far is to move a block (which I guess it rebuilds the workspace?) and you’ll see the counter on first click.

**Comment by SusanRatiLane** [comment]
@josmas Well, the original bug reports do contain screenshots of wildly inaccurate block counts. It's always possible that this behavior was resolved with another fix, but we should check with the community to see if that's true. Some of the users reporting the behavior are power users. They'll be glad to walk through what they're doing to reproduce it.

**Comment by patryk84a** [comment]
When we first click on a block to get focus on it, and then open the context menu, then the counter shows the correct values. However, if we open the context menu on a block that did not have focus, then the counter shows the number of blocks from the previous block that had focus.

**Comment by josmas** [comment]
This seems to be an issue with the multiselect plugin taking over state for the counter.

I've commented out the initialisation of the plugin and it all goes back to normal. Still don't know why it is happening, but I'll follow the lead.

**Comment by josmas** [comment]
Note: the two mentions above are two different fixes for the same issue, one for main in multi-select repo and one for Evan's fork, which I believe is the one used in current Blockly 10.4
